version: '3'

services:

  web:
    build: .
    volumes:
      - static:/static
    env_file:
      - .env
    ports:
      - '8000:8000'

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static:
