# Generated by Django 5.0 on 2023-12-21 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_alter_item_options_item_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(50)], verbose_name='Цена'),
        ),
    ]
