# Generated by Django 5.0 on 2023-12-25 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(unique=True, verbose_name='значение')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('valuefor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.valuefor')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
            bases=('payment.valuefor',),
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('valuefor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.valuefor')),
            ],
            options={
                'verbose_name': 'Налог',
                'verbose_name_plural': 'Налоги',
            },
            bases=('payment.valuefor',),
        ),
    ]
